config/routes.rb
IntercoolerTutorialApp::Application.routes.draw do

  resources :contacts do
    collection do
      get 'contact_rows'
      get 'contacts_table'
      post 'contacts_table'
      post 'email'
    end
    member do
      post 'email'
    end
  end

  get "flash_content" => "contacts#flash_content"

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates_format_of :email, with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  def activate
    self.status = 'active'
    self.save!
  end

  def deactivate
    self.status = 'deactivate'
    self.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.paginate(:page => params[:page])
    render :layout => params['ic-request'].blank?
  end

  def contact_rows
    @contacts = Contact.paginate(:page => params[:page])
    render :partial => 'contact_rows'
  end

  def contacts_table
    if request.post?
      if params['ic-element-id'] == 'activate-btn'
        Contact.find(params['ids']).each &:activate
      else
        Contact.find(params['ids']).each &:deactivate
      end
      render :nothing => true
    else
      @contacts = Contact.paginate(:page => params[:page])
      render :partial => 'contacts_table'
    end
  end

  def email
    if params[:id]
      @contact = Contact.find(params[:id])
    else
      @contact = Contact.new
    end
    @contact.assign_attributes(person_params)
    @contact.valid?
    render :partial => 'email'
  end

  def show
    @contact = Contact.find(params[:id])
    render :layout => params['ic-request'].blank?
  end

  def edit
    @contact = Contact.find(params[:id])
    headers['X-IC-SetLocation'] = edit_contact_path @contact
    render :layout => params['ic-request'].blank?
  end

  def new
    @contact = Contact.new
    headers['X-IC-SetLocation'] = new_contact_path
    render :layout => params['ic-request'].blank?
  end

  def create
    @contact = Contact.create(person_params)
    if @contact.save
      flash[:notice] = 'Created Contact'
      headers['X-IC-SetLocation'] = contact_path @contact
      render action: :show, :layout => params['ic-request'].blank?
    else
      flash[:error] = 'Could not create Contact'
      render action: :new, :layout => params['ic-request'].blank?
    end
  end

  def flash_content
    render :partial => 'layouts/flash_content'
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(person_params)
      flash[:notice] = 'Updated Contact'
      headers['X-IC-SetLocation'] = contact_path @contact
      render action: :show, :layout => params['ic-request'].blank?
    else
      flash[:error] = 'Could not update contact!'
      render action: :edit, :layout => params['ic-request'].blank?
    end
  end

  private

  def person_params
    params.require(:contact).permit(:first_name, :last_name, :email, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_form.html.erb
<%= form_for(@contact, html: {role: 'form'}) do |f| %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div id="emailDiv">
    <%= render :partial => 'email' %>
  </div>

  <div class="form-group">
    <label>Status</label>
    <%= f.select :status, [['Active', 'active'], ['Inactive', 'inactive']], {}, class: 'form-control' %>
  </div>

  <hr/>

  <div class="form-group">

    <button <% if @contact.persisted? %>
            ic-put-to="<%= contact_path @contact %>"
            <% else %>
            ic-post-to="<%= contacts_path %>"
            <% end %>
            ic-target="#content-div"
            class="btn btn-primary">
      Save Contact
    </button>

    <a href="<%= url_for @contact %>" class="btn btn-danger">
      Cancel
    </a>

  </div>

<% end %>

app/views/contacts/_contact_rows.html.erb
<% @contacts.each do |c| %>
  <tr>
    <td>
      <% if c == @contacts.last %>
        <input type="hidden" name="page" value="<%= (params[:page].to_i + 1 if params[:page]) or 2 %>" class="pageHolder"/>
      <% end %>
      <%= c.id %>
    </td>
    <td><%= c.first_name %></td>
    <td><%= c.last_name %></td>
    <td><%= c.email %></td>
    <td><%= link_to "View Contact", c %></td>
  </tr>
<% end %>

app/views/contacts/_contacts_table.html.erb
<table class="table">
  <thead>
    <tr>
      <td></td>
      <td>Id</td>
      <td>Status</td>
      <td>First Name</td>
      <td>Last Name</td>
      <td>Email</td>
    </tr>
  </thead>
  <tbody id="contacts-table-body">
    <% @contacts.each do |c| %>
      <tr>
        <td>
          <input type="checkbox" name="ids[]" value="<%= c.id %>"/>
        </td>
        <td>
          <%= c.id %>
        </td>
        <td><%= c.status %></td>
        <td><%= c.last_name %></td>
        <td><%= c.email %></td>
        <td><%= link_to "View Contact", c %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/_email.html.erb
<div class="form-group <%= 'has-error' unless @contact.errors[:email].empty? %>">
  <label>Email</label>
  <input class="form-control" id="contact_email" name="contact[email]" type="text" value="<%= @contact.email %>"
         ic-post-to="/contacts/<%= @contact.id if @contact.persisted? %>/email"
         ic-transition="none"
         ic-target="#emailDiv">
  <% unless @contact.errors[:email].empty? %>
    <span class="help-block"><%= @contact.errors[:email].join(', ') %></span>
  <% end %>
</div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<hr/>

<%= render :partial => 'contact_form' %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<div class="pull-right">
  <a ic-get-from="<%= new_contact_path %>"
     ic-target="#content-div"
     class="btn btn-primary">Create Contact</a>

  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      Action <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li>
        <a id="activate-btn" ic-post-to="/contacts/contacts_table" ic-include="#contactsForm">Activate</a>
      </li>
      <li>
        <a id="deactivate-btn" ic-post-to="/contacts/contacts_table" ic-include="#contactsForm">Deactivate</a>
      </li>
    </ul>
  </div>

</div>

<form ic-src="/contacts/contacts_table" id="contactsForm" ic-always-update="true">
  <%= render :partial => 'contacts_table' %>
</form>


<div class="pull-right">
  <%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
</div>

app/views/contacts/new.html.erb
<h1>Create Contact</h1>

<hr/>

<%= render :partial => 'contact_form' %>

app/views/contacts/show.html.erb
<h1>Contacts Details</h1>

<hr/>

<div>
  <h4>First Name</h4>
  <%= @contact.first_name %>
</div>

<div>
  <h4>Last Name</h4>
  <%= @contact.last_name %>
</div>

<div>
  <h4>Email</h4>
  <%= @contact.email %>
</div>

<div>
  <h4>Status</h4>
  <%= @contact.status %>
</div>
<hr/>

<a ic-get-from="<%= edit_contact_path @contact %>"
   ic-target="#content-div"
   class="btn btn-primary">Edit Contact</a>

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>

app/views/layouts/_flash_content.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntercoolerTutorialApp</title>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>

    <link rel='stylesheet' type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <link rel='stylesheet' type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"/>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="https://s3.amazonaws.com/intercoolerjs.org/release/intercooler-0.2.0.min.js"></script>

    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Intercooler Tutorial</a>
          </div>
          <!--/.nav-collapse -->
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/contacts">Contacts</a></li>
            </ul>
          </div>
        </div>
        <!--/.container-fluid -->
      </div>
    </div>

    <div id="flash-div" class="container" ic-append-from="/flash_content" ic-deps="*">
      <%= render :partial => '/layouts/flash_content' %>
    </div>

    <div id="content-div" class="container">
      <%= yield %>
    </div>

  </body>
</html>